-- ===================================================================
-- 승정 ERP — 자체 호스팅 Supabase(Docker) 테이블 만들기
-- 사용: Supabase Studio → SQL Editor → 이 파일 전체 붙여넣기 → Run
--       여러 번 실행해도 안전합니다(있는 테이블·데이터는 건드리지 않음).
-- NAS와 집 PC의 Docker Supabase에 똑같이 실행하면 두 곳의 구조가 같아집니다.
-- ⚠ 공개 저장소: 이 파일에 주소·비밀번호·키를 적지 마세요.
-- ===================================================================

-- 1) app_state : 화면 1개 = 문서 1개 (key/value). 거의 모든 화면이 사용
create table if not exists public.app_state (
  key        text primary key,
  value      jsonb,
  src        text,
  updated_at timestamptz default now()
);

-- 2) custom_pages : 업로드한 HTML 화면 (설계/apps.html, 생산/bom.html, 생산/plan.html)
create table if not exists public.custom_pages (
  id         bigserial primary key,
  slug       text,
  title      text,
  html       text,
  updated_at timestamptz default now()
);

-- 3) production : 생산 실적 (생산/production.html, 대시보드/exec-dashboard.html)
create table if not exists public.production (
  id         bigint generated by default as identity primary key,
  pdate      date not null default current_date,
  line       text,
  item       text,
  plan_qty   numeric default 0,
  prod_qty   numeric default 0,
  defect_qty numeric default 0,
  note       text,
  src        text,
  created_at timestamptz default now()
);

-- 4) item_master : 품목 마스터 (생산/itemmaster.html, 기준정보 불러오기)
create table if not exists public.item_master (
  id         bigserial primary key,
  pno text, name text, cat text, spec text, mat text,
  price text, unit text, sup text, remark text,
  updated_at timestamptz default now()
);

-- 5) bom : BOM (대시보드는 lv만 읽음. 편집 화면은 custom_pages의 BOM_LIST)
--    원래 열 구성이 저장소에 남아 있지 않아 넉넉하게 잡았습니다.
create table if not exists public.bom (
  id         bigserial primary key,
  lv         int,
  cat        text,
  pos        int,
  pno        text,
  name       text,
  parent_pno text,
  spec       text,
  mat        text,
  qty        numeric,
  unit       text,
  car_model  text,
  customer   text,
  remark     text,
  updated_at timestamptz default now()
);

-- 6) partners : 거래처 (gubun = 고객사 / 공급사 / 외주)
create table if not exists public.partners (
  id         bigserial primary key,
  gubun      text default '고객사',
  name       text,
  code       text,
  ceo        text,
  tel        text,
  addr       text,
  remark     text,
  updated_at timestamptz default now()
);

-- 7) sales_order : 수주 (대시보드가 읽음)
create table if not exists public.sales_order (
  id         bigserial primary key,
  ono        text,
  cust       text,
  pno        text,
  qty        numeric default 0,
  price      numeric default 0,
  odate      date,
  due        date,
  status     text default '진행',
  remark     text,
  updated_at timestamptz default now()
);

-- 권한: 브라우저(anon 키)에서 읽기·쓰기 허용 (기존 클라우드와 같은 정책, 사내망 전용 전제)
do $$
declare t text;
begin
  foreach t in array array['app_state','custom_pages','production','item_master','bom','partners','sales_order'] loop
    execute format('alter table public.%I enable row level security', t);
    execute format('grant select, insert, update, delete on public.%I to anon, authenticated', t);
    if not exists (select 1 from pg_policies where schemaname='public' and tablename=t and policyname='sj_anon_all') then
      execute format('create policy sj_anon_all on public.%I for all to anon, authenticated using (true) with check (true)', t);
    end if;
  end loop;
end $$;
grant usage, select on all sequences in schema public to anon, authenticated;

-- 실시간(realtime): app_state, production, bom, partners, sales_order
do $$
declare t text;
begin
  if not exists (select 1 from pg_publication where pubname='supabase_realtime') then
    create publication supabase_realtime;
  end if;
  foreach t in array array['app_state','production','bom','partners','sales_order'] loop
    if not exists (select 1 from pg_publication_tables where pubname='supabase_realtime' and schemaname='public' and tablename=t) then
      execute format('alter publication supabase_realtime add table public.%I', t);
    end if;
  end loop;
end $$;

-- 확인: 아래 결과에 7개 테이블이 보이면 성공
select table_name from information_schema.tables
where table_schema='public'
  and table_name in ('app_state','custom_pages','production','item_master','bom','partners','sales_order')
order by 1;
